language: android
jdk: oraclejdk8

branches:
  only:
    - master

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi no ABIs.
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
